### ISSUE TITLE
[!] No podspec found for `flutter_tflite` in `.symlinks/plugins/flutter_tflite/ios`

### ISSUE THREAD

**Issue by alimcevik** [tensorflow/flutter-tflite#192]
### I cannot install pod in Flutter 3.16.7:

```[!] No podspec found for `flutter_tflite` in `.symlinks/plugins/flutter_tflite/ios` ```

```
$flutter run
Changing current working directory to: /Users/alimcevik/Documents/GitHub/[PROJECTNAME]
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install...                                             425ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_tflite` from `.symlinks/plugins/flutter_tflite/ios`
    [!] No podspec found for `flutter_tflite` in `.symlinks/plugins/flutter_tflite/ios`

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:997:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:976:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:975:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:975:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:974:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:422:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 14 Pro Max.
```

### Version info:
```
$ flutter --version
Flutter 3.16.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ef1af02aea (3 weeks ago) • 2024-01-11 15:19:26 -0600
Engine • revision 4a585b7929
Tools • Dart 3.2.4 • DevTools 2.28.5
```

### These methods did not work:
```
flutter clean
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec
rm ios/Podfile
cd ios
pod deintegrate
rm -f Podfile.lock
flutter packages get
pod install --repo-update
```

and

```
flutter clean
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec
rm ios/Podfile
flutter pub get
cd ios
pod install
pod setup
flutter run
```

**Comment by cw-JihunCha** [comment]
any update?

**Comment by jihuncha** [comment]
Same issue to me. Any update??

**Comment by justoverclockl** [comment]
same issue here

**Comment by PrinzWillyM** [comment]
+1

**Comment by yl9111524** [comment]
I have same situation too, but I solve it.

this problem because macos's folder permission
you can try this.

`sudo chown -R $(whoami) /Users/{user}/.pub-cache`

**Comment by furkandemir29** [comment]
+1

**Comment by dcarpencu** [comment]
+1

**Comment by dudago2** [comment]
+1

**Comment by mrpuryansyah** [comment]
+1

**Comment by vishhmakasana** [comment]
@furkandemir29  @mrpuryansyah @emrullahkeles @dudago2 @dcarpencu

I was getting somewhat same error, here is what I did to resolve it. 

Error : [!] No podspec found for `tflite_v2` in `.symlinks/plugins/tflite_v2/ios`

I checked the directory .symlinks/plugins/tflite_v2/ios, there tflite.podspec file was present.
So I renamed it to tflite_v2.podspec. After that again I tried to do pod install but got below error.

[!] The name of the given podspec `tflite` doesn't match the expected one `tflite_v2`

To resolve that I have changed this inside podspec file

  s.name             = 'tflite_v2'

After that its started working.

**Comment by bijeaylimbu** [comment]
https://github.com/tensorflow/flutter-tflite/issues/192#issuecomment-2390844134 this works thank you

**Comment by evchibo** [comment]
> [#192 (comment)](https://github.com/tensorflow/flutter-tflite/issues/192#issuecomment-2390844134) this works thank you

This worked for me
