### ISSUE TITLE
Failed to lookup symbol 'TfLiteInterpreterOptionsCreate': dlsym(RTLD_DEFAULT, TfLiteInterpreterOptionsCreate): symbol not found

### ISSUE THREAD

**Issue by shuizhuyu1015** [tensorflow/flutter-tflite#221]
I reported an error while exporting tflite_flutter as framework through the flutter module to the iOS native project.
flutter 3.7.0，xcode 14.
`Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'TfLiteInterpreterOptionsCreate': dlsym(RTLD_DEFAULT, TfLiteInterpreterOptionsCreate): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
#1      TensorFlowLiteBindings._TfLiteInterpreterOptionsCreatePtr (package:tflite_flutter/src/bindings/tensorflow_lite_bindings_generated.dart:336)
#2      TensorFlowLiteBindings._TfLiteInterpreterOptionsCreate (package:tflite_flutter/src/bindings/tensorflow_lite_bindings_generated.dart)
#3      TensorFlowLiteBindings.TfLiteInterpreterOptionsCreate (package:tflite_flutter/src/bindings/tensorflow_lite_bindings_generated.dart)
#4      new InterpreterOptions (package:tflite_flutter/src/interpreter_options.dart:36)
#5      Detector._loadModel (package:tf_module/service/detector_service.dart:109)
#6      Detector.start (package:tf_module/service/detector_service.dart:99)
<asynchronous suspension>`

**Comment by OdilonDamasceno** [comment]
Same problem :(

**Comment by shuizhuyu1015** [comment]
> 嘿，错误解决了吗？ 我也遇到了同样的问题。你能帮帮我吗？

Thank you very much. Your guidance is very good. I solved it by manually importing TensorFlowLiteC. I will adopt your method.
